name: r2s Lean版openwrt minimal(EricMod)

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/r2s_lean_minimal.yml'
  schedule:
    - cron: '10 08 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository == 'ericvwv/nanopi-openwrt'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: . 1_initialization_environment.sh

      - name: Clone Source
        run: . 2_clone_source.sh master-v19.07.1 rk3328

      - name: Patch Kernel
        run: . patch_kernel_5.4.sh

      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          cat ../minimal_config.seed >> ../base_rk3328.seed
          cat ../base_rk3328.seed > configs/config_rk3328
                    echo '
          # CONFIG_PACKAGE_ipv6helper=n
          # CONFIG_PACKAGE_dnsmasq_full_dhcpv6=n
          CONFIG_PACKAGE_dnsmasq-full=y
          CONFIG_PACKAGE_dnsmasq_full_dhcp=y
          CONFIG_OPENSSL_ENGINE_BUILTIN=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_NPN=y
          CONFIG_PACKAGE_autocore=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_diffutils=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_pv=y
          CONFIG_PACKAGE_pigz=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_losetup=y
          # CONFIG_PACKAGE_luci-app-frpc=n
          CONFIG_LIBSODIUM_MINIMAL=y
          # CONFIG_PACKAGE_ddns-scripts_aliyun=n
          # CONFIG_PACKAGE_ddns-scripts_cloudflare.com-v4=n
          CONFIG_PACKAGE_luci-app-cpufreq=y
          # CONFIG_PACKAGE_luci-app-ssr-plus=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_DNS2SOCKS=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=n
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=n
          # CONFIG_PACKAGE_luci-app-unblockmusic=n
          # CONFIG_PACKAGE_luci-app-v2ray-server=n
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-app-uhttpd=y
          # CONFIG_PACKAGE_luci-app-unblockmusic=n
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          # CONFIG_UnblockNeteaseMusic_Go=n
          # CONFIG_UnblockNeteaseMusic_NodeJS=n
          # CONFIG_PACKAGE_luci-app-samba=n
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
          CONFIG_PACKAGE_ntfs-3g=y
          # CONFIG_PACKAGE_luci-app-openclash=n
          # CONFIG_PACKAGE_luci-app-diskman=n
          CONFIG_PACKAGE_luci-app-zerotier=y
          # CONFIG_PACKAGE_luci-app-r2sflasher=n
          # CONFIG_PACKAGE_luci-app-aria2=n
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-pppoe-relay is not set
          # CONFIG_PACKAGE_luci-app-pppoe-server is not set
          # CONFIG_PACKAGE_luci-app-pptp-vpnserver-manyusers is not set
          # CONFIG_PACKAGE_luci-app-sqm is not set
          # CONFIG_PACKAGE_luci-app-ssr-python-pro-server is not set
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Socks is not set
          # CONFIG_TARGET_ROOTFS_TARGZ is not set
          # CONFIG_OPENSSL_ENGINE_BUILTIN_DEVCRYPTO is not set
          # CONFIG_PACKAGE_kmod-crypto-authenc is not set
          # CONFIG_PACKAGE_kmod-cryptodev is not set
          # CONFIG_PACKAGE_libopenssl-devcrypto is not set
          # CONFIG_V2RAY_COMPRESS_UPX is not set
          ' >> configs/config_rk3328
          cd friendlywrt
          git remote add upstream https://github.com/coolsnowwolf/openwrt && git fetch upstream
          git checkout upstream/lede-17.01 -b tmp
          git rm README.md
          git commit -m 'reset'
          git checkout master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          rm -f target/linux/rockchip-rk3328/patches-4.14/0001-net-thunderx-workaround-BGX-TX-Underflow-issue.patch target/linux/generic/hack-4.14/999-net-patch-linux-kernel-to-support-shortcut-fe.patch
          git checkout upstream/lede-17.01 -- feeds.conf.default && sed -i -E 's/#(src-git.+)(helloworld.+)/\1\2/' feeds.conf.default
          curl 'https://git.openwrt.org/?p=openwrt/openwrt.git;a=patch;h=22378beb581b113def1dc392ef75306a2168a163' | git apply --reject - || true
          . ../../3_prepare_packages.sh
          . ../../add_openclash.sh
          . ../../add_passwall.sh
          git apply ../../enable_autocore.diff
          sed -i 's/@LINUX_5_4//' package/lean/luci-app-flowoffload/Makefile
          . ../../5_mods.sh
          mv ../../scripts/check_wan4.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/check_wan4.sh &' package/base-files/files/etc/rc.local
          mv ../../scripts/autoupdate.sh package/base-files/files/root/au.sh && chmod +x package/base-files/files/root/au.sh

      - name: Build FriendlyWrt
        run: . 4_build_image.sh friendlywrt-rk3328 nanopi_r2s.mk

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          . x_assemble_artifact.sh
          release_tag="R2S-Minimal-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
